import { render, screen, fireEvent } from '@testing-library/react';
import StartScreen from './StartScreen'; // Adjust the import path as necessary

describe('StartScreen component', () => {
  const mockOnStart = jest.fn(); // Mock function

  afterEach(() => {
    jest.clearAllMocks(); // Clear mock function calls after each test
  });

  test('renders Welcome message and instructions', () => {
    render(<StartScreen onStart={mockOnStart} />);

    // Assert that the welcome message is rendered
    expect(screen.getByText(/Welcome to the Chat GPT Quiz!/i)).toBeInTheDocument();

    // Assert that the instructions are rendered
    expect(screen.getByText(/You'll be presented with 10 random questions generated by Chat GPT./i)).toBeInTheDocument();
    expect(screen.getByText(/You have 15 seconds to answer and each question is worth 1 point/i)).toBeInTheDocument();
    expect(screen.getByText(/Good Luck!/i)).toBeInTheDocument();
  });

  test('calls onStart when Start Quiz button is clicked', () => {
    render(<StartScreen onStart={mockOnStart} />);

    const startButton = screen.getByText(/Start Quiz/i);
    fireEvent.click(startButton); // Simulate button click

    expect(mockOnStart).toHaveBeenCalledTimes(1); // Check that the mock function was called once
  });
});