import React from 'react';

interface StartScreenProps {
  onStart: () => void; // Prop to handle the start action
}

const StartScreen: React.FC<StartScreenProps> = ({ onStart }) => {
  return (
    <div className="start-screen max-h-[400px] max-w-[350px] h-full flex flex-col place-content-between">
      <h1 className='text-3xl font-bold'>Welcome to the Chat GPT Quiz!</h1>
      <div>
          <p>You'll be presented with 10 random questions generated by Chat GPT.</p>
          <br/>
          <p>You have 15 seconds to answer and each question is worth 1 point</p>
          <br/>
          <p>Good Luck!</p>
      </div>
      <button onClick={onStart} className='btn btn-primary'>Start Quiz</button>
    </div>
  );
};

export default StartScreen;